### ISSUE TITLE
Detect changes in yaw?

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_MMA8451_Library#16]
I've figured out I can check `mma.x` and `mma.y` quite easily to see what's up with the roll and pitch of the MMA8451, but how can I find out changes in yaw?

**Comment by caternuson** [comment]
You can't do that with just an accelerometer. You would need something with a gyro as well. Checkout the sensor with combined accel/gyro:
https://www.adafruit.com/category/521
Also some good info here:
https://learn.adafruit.com/ahrs-for-adafruits-9-dof-10-dof-breakout
