### ISSUE TITLE
I2C Pin Selection

### ISSUE THREAD

**Issue by Pulsar07** [adafruit/Adafruit_MMA8451_Library#19]
The lib does not provide a possibility to select non default I2C pins. 
It would be very helpful when an additional begin method provides additional parameters:
mma.begin(SDA_Pin, SCL_Pin, I2CAddr);

Regards
Rainer

**Comment by Colin-at-511100471793** [comment]
Bump !!  same deal here, it's kinda a pain to re-define it all

**Comment by ladyada** [comment]
check this resolved ESP32 issue
https://github.com/espressif/arduino-esp32/issues/3779
