### ISSUE TITLE
Bit shift operation losing sign value

### ISSUE THREAD

**Issue by baurandr** [adafruit/Adafruit_MMA8451_Library#25]
- Arduino board:  HUZZAH32

- Arduino IDE version (found in Arduino -> About Arduino menu):  Using ESPHome
```
board: featheresp32; framework: arduino; platform: platformio/espressif32@3.2.0
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
Library Manager: Installing Hash
Library Manager: Already installed, built-in library
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <Adafruit MMA8451 Library> 1.2.0
|   |-- <Adafruit BusIO> 1.9.3
|   |   |-- <Wire> 1.0.1
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0.1
|   |-- <Adafruit Unified Sensor> 1.1.4
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.3.0
|   |-- <AsyncTCP-esphome> 1.2.2
|   |-- <Crypto> 0.2.0
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <noise-c> 0.1.3
|   |-- <libsodium> 1.10018.1
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
|-- <SPI> 1.0
```

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

Bit shift operation in Adafruit_MMA8451.cpp appears to be losing sign during right shift:
```
  x = ((int16_t(buffer[0]) << 8) | int16_t(buffer[1])) >> 2;
  y = ((int16_t(buffer[2]) << 8) | int16_t(buffer[3])) >> 2;
  z = ((int16_t(buffer[4]) << 8) | int16_t(buffer[5])) >> 2;
```

I did not have this issue when using Adafruit_MMA8451_Library 1.1.0.  The sign bit was preserved.

For my code:
```
Adafruit_MMA8451 mma = Adafruit_MMA8451();
mma.read();
```

When reading back mma.x, mma.y, mma.z they are always positive integers.
I repaired it in my code by doing the following:
```
  mma.x <<= 2;
  mma.x >>= 2;
  mma.y <<= 2;
  mma.y >>= 2;
  mma.z <<= 2;
  mma.z >>= 2;
```

**Comment by caternuson** [comment]
Weird, not sure why this didn't show up in the testing done for #24. But rerunning same example, seeing it now:
![Screenshot from 2021-10-10 14-56-32](https://user-images.githubusercontent.com/8755041/136714197-dcf3f638-3a00-4adc-860d-f7c682323487.png)

Just need to rework the casting. Will PR a fix.

**Comment by caternuson** [comment]
Please try the 1.2.1 release when it becomes available:
https://github.com/adafruit/Adafruit_MMA8451_Library/releases/tag/1.2.1

**Comment by baurandr** [comment]
Ok, thank you for the quick fix, I will!

**Comment by caternuson** [comment]
Closing. Should be fixed by release linked above.
