### ISSUE TITLE
Invalid bit mask for data rate?

### ISSUE THREAD

**Issue by PrzemoF** [adafruit/Adafruit_MMA8451_Library#3]
void Adafruit_MMA8451::setDataRate(mma8451_dataRate_t dataRate)
{
uint8_t ctl1 = readRegister8(MMA8451_REG_CTRL_REG1);
ctl1 &= ~(0x28); // mask off bits
ctl1 |= (dataRate << 3);
writeRegister8(MMA8451_REG_CTRL_REG1, ctl1);
}

I think it should be:
ctl1 &= ~(0x38); // mask off bits
otherwise bit 4 is not masked (data rate is in bits 3,4 and 5)

**Comment by microbuilder** [comment]
Good eye, I just pushed an update out for this.
