### ISSUE TITLE
Error Compiling demo

### ISSUE THREAD

**Issue by WillyKirsch** [adafruit/Adafruit_MMA8451_Library#5]
Hello, I'm trying to compile the demo and throws this error:

In file included from MMA8451demo.ino:21:0:
C:\Users\Guillermo\Documents\Arduino\libraries\Adafruit_MMA8451/Adafruit_MMA8451.h:93:8: error: conflicting return type specified for 'virtual bool Adafruit_MMA8451::getEvent(sensors_event_t_)'
   bool getEvent(sensors_event_t *event);
        ^
In file included from C:\Users\Guillermo\Documents\Arduino\libraries\Adafruit_MMA8451/Adafruit_MMA8451.h:27:0,
                 from MMA8451demo.ino:21:
C:\Users\Guillermo\Documents\Arduino\libraries\Adafruit_Sensor/Adafruit_Sensor.h:146:16: error:   overriding 'virtual void Adafruit_Sensor::getEvent(sensors_event_t_)'
   virtual void getEvent(sensors_event_t*);
                ^

Please Help!!

**Comment by microbuilder** [comment]
See this issue for details: https://github.com/adafruit/Adafruit_MMA8451_Library/issues/4

**Comment by WillyKirsch** [comment]
Thank you!! I missed to update adafruit sensor library... :P
